version: '3.8'

services:
  database:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wordsdb
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql


  app:
    build: .
    environment:
      DATABASE_URL: postgres://user:password@database:5432/wordsdb?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - database

volumes:
  database_data:
