apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: atlas-db-migrations
    files:
      - ./001_initial_schema.sql
      - ./002_add_user_settings.sql
      - ./003_predefined_tags.sql
      - ./004_async_processing_and_demo.sql
      - atlas.sum
    options:
      disableNameSuffixHash: true
